### ISSUE TITLE
ReferenceError: crypto is not defined

### ISSUE THREAD

**Issue by ltfschoen** [blake-regalia/belt#1]
crypto.ts was introduced in this commit but it is all commented out https://github.com/blake-regalia/belt/blob/da7222c73ce46cfef54b76e058ba887615459029/src/crypto.ts

if i run this file https://github.com/svub/nunya/pull/33/files#diff-46e137c2819340c4616c8f780dd1f04b7e115a09254af3788e3ce6b39ca7af9a it funds this line of code using this repo https://github.com/svub/nunya/pull/33/files#diff-810c10d3f20b10a4e1561990fb4c64098f9cf95600d44385c6859d882ee647a9R37 and gives error `ReferenceError: crypto is not defined`

the utils.js and _assert.js files aren't there either. 
Is this utils.js file meant to be referring to this other repo https://github.com/SolarRepublic/neutrino/blob/main/src/util.ts ?

**Comment by blake-regalia** [comment]
I think `crypto` not being defined is a matter of [`globalThis.crypto`](https://developer.mozilla.org/en-US/docs/Web/API/Crypto) not being available in your environment. The file in this repo is not related to that error. I think the latest version of this package is a breaking change compared to the code that sample was based off of. Have you tried downgrading or pinning the dependency version?

**Comment by ltfschoen** [comment]
is the `crypto` used here supposed to be from dependency https://github.com/SolarRepublic/crypto (can't find `randomUUID` in that repo) or from the built-in NPM https://www.npmjs.com/package/crypto

**Comment by ltfschoen** [comment]
Polyfill thankfully as suggested here https://www.npmjs.com/package/@noble/secp256k1 helped overcome error `ReferenceError: crypto is not defined` when performing `await sha256`
```
import { webcrypto } from 'node:crypto';
// @ts-ignore
if (!globalThis.crypto) globalThis.crypto = webcrypto;
```
